# Generated by Django 4.2.1 on 2023-05-30 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_profileimage_alter_groceries_name_usersrecipes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersRecipes',
            new_name='UsersRecipesCreate',
        ),
    ]
